apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-html
data:
  index.html: |
    <!DOCTYPE html>
    <html>
      <head>
        <title>Welcome</title>
        <!-- Include Bootstrap CSS from CDN -->
        <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet">
      </head>
      <body>
        <div class="container">
          <div class="jumbotron mt-5">
            <h1 class="display-4">Hello!</h1>
            <p class="lead">Are you ready...</p>
          </div>
        </div>
      </body>
    </html>
  
  stub_status_nginx.conf: |
    server {
        listen 80 default_server;
        listen [::]:80 default_server;
        root /var/www/html;
        index index.html index.htm index.nginx-debian.html;
        server_name _;
        location / {
            try_files $uri $uri/ =404;
        }
        location /nginx_status {
          stub_status;
          allow nginx-service;
          deny all;
        }
    }